---
hostname: coin-ops-test

admin_user: jpnance
admin_email: jpnance@gmail.com

apps_dir: /home/{{ admin_user }}/apps
ops_dir: /home/{{ admin_user }}/ops

docker_network: coinflipper

apps:
  - name: Coinflipper Login
    slug: login
    repo: https://github.com/jpnance/CoinflipperLogin
    dest: CoinflipperLogin
    domain: login.coinflipper.org
    port: 5422
    monotonic:
      - users

  - name: SubContest
    slug: subcontest
    repo: https://github.com/jpnance/SubContest
    dest: SubContest
    domain: subcontest.coinflipper.org
    port: 7811
    monotonic:
      - games
      - users

  - name: Summer Classics
    slug: classix
    repo: https://github.com/jpnance/SummerClassics
    dest: SummerClassics
    domain: classics.coinflipper.org
    port: 9895
    monotonic:
      - classics
      - games
      - players
      - users

  - name: Pick-a-Hit
    slug: pickahit
    repo: https://github.com/jpnance/pickahit
    dest: pickahit
    domain: pickahit.coinflipper.org
    port: 2814
    monotonic:
      - games
      - players
      - users

  - name: Primetime Soap Operas
    slug: pso
    repo: https://github.com/jpnance/PSO
    dest: PSO
    domain: thedynastyleague.com
    port: 9528
    monotonic:
      - budgets
      - contracts
      - franchises
      - games
      - people
      - picks
      - players
      - regimes
      - transactions
