---
hostname: cloudbreak

admin_user: jpnance
admin_email: jpnance@gmail.com

apps_dir: /home/{{ admin_user }}/apps

docker_network: coinflipper

apps:
  - name: Coinflipper Login
    slug: login
    repo: https://github.com/jpnance/CoinflipperLogin
    domain: login.coinflipper.org
    type: node
    port: 5422
    monotonic:
      - users

  - name: SubContest
    slug: subcontest
    repo: https://github.com/jpnance/SubContest
    domain: subcontest.coinflipper.org
    type: node
    port: 7811
    monotonic:
      - games
      - users

  - name: Summer Classics
    slug: classix
    repo: https://github.com/jpnance/SummerClassics
    domain: classics.coinflipper.org
    type: node
    port: 9895
    monotonic:
      - classics
      - games
      - players
      - users

  - name: Pick-a-Hit
    slug: pickahit
    repo: https://github.com/jpnance/pickahit
    domain: pickahit.coinflipper.org
    type: node
    port: 2814
    monotonic:
      - games
      - players
      - users

  - name: Primetime Soap Operas
    slug: pso
    repo: https://github.com/jpnance/PSO
    domain: thedynastyleague.com
    type: node
    port: 9528
    monotonic:
      - budgets
      - contracts
      - franchises
      - games
      - people
      - picks
      - players
      - regimes
      - transactions

  - name: ProWriterAlpha
    slug: pwa
    repo: https://github.com/jpnance/ProWriterAlpha
    domain: pwa.coinflipper.org
    type: static
    deploy_cmd: "true"

  - name: Coinflipper
    slug: coinflipper
    repo: https://github.com/jpnance/Coinflipper
    domain: coinflipper.org
    type: static
    deploy_cmd: "true"

  - name: BBGPBG
    slug: bbgpbg
    domain: props.coinflipper.org
    type: upload
