---
hostname: cloudbreak

admin_user: jpnance
admin_email: jpnance@gmail.com
ansible_become_password: "{{ vault_admin_password_plaintext }}"

apps_dir: /home/{{ admin_user }}/apps
ops_dir: /home/{{ admin_user }}/ops

docker_network: coinflipper

ssh_pubkeys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKuTniiLi5+CqhwTFBIUCbBrN+BVkJvgMBbm83JkM6QF jpnance@countercheck"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEX83/A/iIr0kjKky3yHQGK5hTHceBPheF/EZp6GoHF9 jpnance@salvage"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIP2/rnsL5jNVgJSz8Gmrt3Jw9C5eaIDI7W5UuI/PRpH jpnance@lifeform"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINeQcID7PFRkqFgzAfR2IGP7qu9ZFi9JLNXZ8NslsbK/ jpnance@sherpa"
